### ISSUE TITLE
ng serve error

### ISSUE THREAD

**Issue by k-schneider** [AngularFirebase/70-ngrx-angularfire2-state-changes#1]
I cloned  the project, ran "npm install" (also tried "yarn") and received this error:

```
ERROR in TypeError: Cannot read property 'length' of undefined
    at createSourceFile (D:\Dev\tmp\ngx-angularfire2-firestore-example\node_modules\typescript\lib\typescript.js:13351:109)
    at parseSourceFileWorker (D:\Dev\tmp\ngx-angularfire2-firestore-example\node_modules\typescript\lib\typescript.js:13283:26)
    at Object.parseSourceFile (D:\Dev\tmp\ngx-angularfire2-firestore-example\node_modules\typescript\lib\typescript.js:13209:26)
    at Object.createSourceFile (D:\Dev\tmp\ngx-angularfire2-firestore-example\node_modules\typescript\lib\typescript.js:13050:29)
    at VirtualFileStats.getSourceFile (D:\Dev\tmp\ngx-angularfire2-firestore-example\node_modules\@ngtools\webpack\src\compiler_host.js:67:35)
    at WebpackCompilerHost.getSourceFile (D:\Dev\tmp\ngx-angularfire2-firestore-example\node_modules\@ngtools\webpack\src\compiler_host.js:207:38)
    at findSourceFile (D:\Dev\tmp\ngx-angularfire2-firestore-example\node_modules\typescript\lib\typescript.js:72860:29)
    at processImportedModules (D:\Dev\tmp\ngx-angularfire2-firestore-example\node_modules\typescript\lib\typescript.js:73032:25)
    at findSourceFile (D:\Dev\tmp\ngx-angularfire2-firestore-example\node_modules\typescript\lib\typescript.js:72908:17)
    at processImportedModules (D:\Dev\tmp\ngx-angularfire2-firestore-example\node_modules\typescript\lib\typescript.js:73032:25)
    at findSourceFile (D:\Dev\tmp\ngx-angularfire2-firestore-example\node_modules\typescript\lib\typescript.js:72908:17)
    at args (D:\Dev\tmp\ngx-angularfire2-firestore-example\node_modules\typescript\lib\typescript.js:72797:85)
    at getSourceFileFromReferenceWorker (D:\Dev\tmp\ngx-angularfire2-firestore-example\node_modules\typescript\lib\typescript.js:72770:34)
    at processSourceFile (D:\Dev\tmp\ngx-angularfire2-firestore-example\node_modules\typescript\lib\typescript.js:72797:13)
    at processRootFile (D:\Dev\tmp\ngx-angularfire2-firestore-example\node_modules\typescript\lib\typescript.js:72652:13)
    at D:\Dev\tmp\ngx-angularfire2-firestore-example\node_modules\typescript\lib\typescript.js:71810:60
```

During package restore there is a warning that might be related:

```
@angular/compiler-cli@5.0.2 requires typescript@'>=2.4.2 <2.5.0' but 2.6.1 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.
```

**Comment by cissecedric** [comment]
Hi @k-schneider I have the same error have you solved it?

**Comment by codediodeio** [comment]
@cissecedric Make sure to create the file `src/environments/environment.ts` with your Firebase project credentials - specific instructions are in the readme.

**Comment by codediodeio** [comment]
Actually more detailed instructions are provided here https://github.com/codediodeio/angular-firestarter

**Comment by cissecedric** [comment]
Thank you @codediodeio, it works fine with environment files,  and I'll actually try to implement ngrx in the code you recommend to use ( https://github.com/codediodeio/angular-firestarter)
